name: Backend CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: medpark_user
          POSTGRES_PASSWORD: medpark_password
          POSTGRES_DB: medpark_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          ruff check .
          ruff format . --check
      
      - name: Run tests with Pytest
        env:
          DATABASE_URL: "postgresql://medpark_user:medpark_password@localhost:5432/medpark_db_test"
          PYTHONPATH: .
        run: pytest